server:
  port: 8080
  servlet:
    context-path: /dept-svc

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/departmentdb
  application:
    name: ems-department-service
  config:
    import: optional:configserver:http://localhost:8082